from pybricks.hubs import PrimeHub
from pybricks.pupdevices import Motor, ColorSensor, UltrasonicSensor, ForceSensor
from pybricks.parameters import Button, Color, Direction, Port, Side, Stop
from pybricks.robotics import DriveBase, GyroDriveBase
# Manually added GyroDriveBase
from pybricks.tools import wait, StopWatch

hub = PrimeHub()
# Everything above is auto generated by Pybricks
# Initialize both motors. In this example, the motor on the
# left must turn counterclockwise to make the robot go forward.
left_motor = Motor(Port.C, Direction.COUNTERCLOCKWISE)
right_motor = Motor(Port.D)
# Initialize the drive base. In this example, the wheel diameter is 62.5mm (Big Wheels).
# The distance between the two wheel-ground contact points is 136mm.
drive_base = GyroDriveBase(left_motor, right_motor, wheel_diameter=62.5, axle_track=136)
drive_base.settings(400, 500, 100, 200)
# settings 
# (straight_speed, straight_acceleration, 
# turn_rate, turn_acceleration)
# Initialize motors on port A and E.
track_motor = Motor(Port.A)
gripper_motor = Motor(Port.E)
# Make both motors run at 500 degrees per second.
# Change motor names from track and gripper to whatever you want
#track_motor.run(500)
#gripper_motor.run(500)
# Wait for three seconds.
wait(3000)
def power_plant():
    # Make sure to make seperate functions for missions whenever you are coding
    drive_base.straight(100)
    # Basic piece of turn code/Turn around clockwise by 180 degrees.
    drive_base.turn(90)
    drive_base.straight(100)
    # a basic piece of drive code/makes the robot go forward 100 mm


def tv():
    # Drive forward by 500mm (half a meter).
    drive_base.straight(1000)

    # Turn around clockwise by 180 degrees.
    drive_base.turn(180)
def bob():
    # Drive forward again to get back to the start.
    drive_base.straight(1000)

    # Turn around counterclockwise.
    drive_base.turn(-180)
def run2_func():
    """ Combines all of the individual parts of run2 into 1 variable to run"""
    tv()
    bob()
while True:
    """ This is how to use the left and right button on the robot"""
    pressed = hub.buttons.pressed() 
    if (Button.LEFT in pressed):
        run2_func()
        hub.light.on(Color.GREEN)

    if (Button.RIGHT in pressed):
        power_plant()
        hub.light.on(Color.RED)
